# Generated by Django 5.0.6 on 2026-07-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_bill_billed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='billed_by_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
